package edu.byui.cit.text;

import android.util.Log;
import android.view.View;
import android.widget.AdapterView;

import edu.byui.cit.calc360.Calc360;


public abstract class ItemSelectedHandler implements ItemSelectedListener {
	/* progs, nextIsProgrammatic, and replacing onItemSelected with
	 * itemSelected are all necessary because the Android Spinner class
	 * does not distinguish between selection events generated by the
	 * app and those generated by the user. */
	private long progs = 0;

	@Override
	public final void nextIsProgrammatic() {
		++progs;
	}

	@Override
	public final void onItemSelected(
			AdapterView<?> parent, View view, int pos, long id) {
		if (progs > 0) {
			--progs;
		}
		else {
			try {
				itemSelected(parent, view, pos, id);
			}
			catch (NumberFormatException ex) {
				// Do nothing
			}
			catch (Exception ex) {
				Log.e(Calc360.TAG, "exception", ex);
			}
		}
	}

	public void itemSelected(
			AdapterView<?> parent, View view, int pos, long id) {
	}

	@Override
	public void onNothingSelected(AdapterView<?> parent) {
	}
}
