@startuml
skinparam classAttributeIconSize 0

title High Level Classes in Calc 360
abstract AppCompatActivity
abstract Fragment
abstract AppCompatButton

package edu.byui.cit.calc360 {
	class Calc360
	class CalcButton
	class CalcDescriptor
	abstract CalcFragment
	abstract Converter
	abstract Descriptor
	class Descriptors <<(S, #FF7700) Singleton>>
	class GroupDescriptor
	class GroupFragment
	class IndexArray
	abstract OmniFragment
	class OrderedIndexArray
	abstract SolveEquation
	abstract SolveSeries

	AppCompatActivity <|-- Calc360
	AppCompatButton <|-- CalcButton

	Descriptor <|-- CalcDescriptor
	Descriptor <|-- GroupDescriptor
	Descriptors *-- Descriptor

	Calc360 *-right- OmniFragment
	Fragment <|-- OmniFragment
	OmniFragment <|-- CalcFragment
	CalcFragment <|-- Converter
	CalcFragment <|-- GroupFragment
	CalcFragment <|-- SolveSeries
	SolveSeries <|-- SolveEquation

	GroupFragment *-- CalcButton
	CalcFragment .right. Descriptor

	IndexArray <|-- OrderedIndexArray
	hide IndexArray
	hide OrderedIndexArray

	note left of CalcFragment
	Each calculator that does not
	fit the note for SolveSeries,
	SolverEquation, or Converter
	should extend CalcFragment.
	end note

	note bottom of Converter
	Each calculator that simply converts
	values from one unit to another
	unit should extend Converter.
	end note

	note bottom of SolveSeries
	Each calculator that solves for
	the values in a series of equations
	should extend SolveSeries.
	end note

	note top of SolveEquation
	Each calculator that solves for
	the values in a single equation
	should extend SolveEquation.
	end note
}


newpage
title Calc 360 Classes that Wrap Android User Interface Components
package edu.byui.cit.text {
	interface TextChangeListener
	interface ItemSelectedListener
	interface DateChangeListener
	interface ClickListener

	class Handler
	abstract DateChangeHandler
	abstract ItemSelectedHandler
	abstract TextChangeHandler

	DateChangeListener <|... DateChangeHandler
	Handler <|-- DateChangeHandler
	ItemSelectedListener <|... ItemSelectedHandler
	Handler <|-- ItemSelectedHandler
	TextChangeListener <|... TextChangeHandler
	Handler <|-- TextChangeHandler

	class ButtonWrapper
	abstract ControlWrapper
	class DateWrapper
	class EditAngle
	class EditCur
	class EditDec
	class EditFrac
	class EditInt
	class EditPerc
	abstract EditWrapper
	abstract InputWrapper
	class RadioWrapper
	abstract SpinContainer
	class SpinInt
	class SpinProperty
	class SpinString
	class SpinUnit
	abstract SpinWrapper
	class TextWrapper

	ControlWrapper <|-- ButtonWrapper
	ControlWrapper <|-- InputWrapper
	ControlWrapper <|-- RadioWrapper
	ControlWrapper <|-- TextWrapper
	InputWrapper <|-- DateWrapper

	InputWrapper <|-- EditWrapper
	EditWrapper <|-- EditCur
	EditWrapper <|-- EditDec
	EditWrapper <|-- EditFrac
	EditWrapper <|-- EditInt
	EditWrapper <|-- EditPerc
	EditDec <|-- EditAngle

	InputWrapper <|-- SpinWrapper
	SpinWrapper <|-- SpinInt
	SpinWrapper <|-- SpinContainer
	SpinContainer <|-- SpinProperty
	SpinContainer <|-- SpinUnit
	SpinWrapper <|-- SpinString

	note as WrapperNote
	Every user interface component in a
	calculator should be wrapped inside
	one of the concrete wrapper classes.
	end note
}


newpage
title Calc 360 Classes that Convert between Units
package edu.byui.cit.units {
	class Angle <<(S, #FF7700) Singleton>>
	class Area <<(S, #FF7700) Singleton>>
	abstract Container<? extends Named>
	class DataSize <<(S, #FF7700) Singleton>>
	class Force <<(S, #FF7700) Singleton>>
	class Frequency <<(S, #FF7700) Singleton>>
	class FuelEffic <<(S, #FF7700) Singleton>>
	class Length <<(S, #FF7700) Singleton>>
	class Mass <<(S, #FF7700) Singleton>>
	class Money <<(S, #FF7700) Singleton>>
	class Named
	class Pressure <<(S, #FF7700) Singleton>>
	abstract Property
	class Speed <<(S, #FF7700) Singleton>>
	class Temperature <<(S, #FF7700) Singleton>>
	class Time <<(S, #FF7700) Singleton>>
	class Unit
	class Volume <<(S, #FF7700) Singleton>>
	class World <<(S, #FF7700) Singleton>>

	Named <|-- Container
	Container <|-- World
	World *-left- Property
	Property *-right- Unit
	Container <|-- Property
	Property <|-- Angle
	Property <|--- Area
	Property <|---- DataSize
	Property <|-- Force
	Property <|--- Frequency
	Property <|---- FuelEffic
	Property <|-- Length
	Property <|--- Mass
	Property <|---- Money
	Property <|-- Pressure
	Property <|--- Speed
	Property <|---- Temperature
	Property <|--- Time
	Property <|---- Volume
	Container <|-- Unit
}
@enduml
