@startuml
[*] --> Cleared

Cleared --> Cleared : C CE 0 =
Cleared --> AccumLeft : 1 2 3 4 5 6 7 8 9 .
Cleared --> Result : +/- sqrt
Cleared --> Pending : + - * /

AccumLeft --> Cleared : C CE
AccumLeft --> AccumLeft : 0 1 2 3 4 5 6 7 8 9 .
AccumLeft --> Result : +/- sqrt
AccumLeft --> Pending : + - * /
AccumLeft --> AccumLeft : =

Pending --> Cleared : C
Pending --> Pending : CE 0 +/= sqrt
Pending --> AccumRight : 1 2 3 4 5 6 7 8 9 .
Pending --> Pending : + - * /

AccumRight --> Cleared : C
AccumRight --> Pending : CE
AccumRight --> AccumRight : 0 1 2 3 4 5 6 7 8 9 .
AccumRight --> Result : +/- sqrt
AccumRight --> Result : =

Result --> Cleared : C CE
Result --> Result : +/- sqrt
@enduml
